version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: shop-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local